printshellcmds: yes
sample_metadata: config/sample_metadata.csv
generate_data:
  seed: 123456.0
  'n': 10000.0
wrangle:
  nrow: 4
plot:
  color: red
scater_plot:
  dot_col: blue
histogram:
  bar_col: blue
  bar_fill: green2
  nbins: 10.0
vln_plot:
  param1: orange
